import blogImage1 from "@/assets/img/blog/blog__1.jpg";
import blogImage2 from "@/assets/img/blog/blog__2.png";
import blogImage3 from "@/assets/img/blog/blog__3.png";
import blogImage4 from "@/assets/img/blog/blog__4.png";
import blogImage5 from "@/assets/img/blog/blog__5.png";
import blogImage6 from "@/assets/img/blog/blog__6.png";
import blogImage7 from "@/assets/img/blog/blog__7.png";
import blogImage8 from "@/assets/img/blog/blog__8.png";
import blogImage9 from "@/assets/img/blog/blog__9.png";
import blogImage10 from "@/assets/img/blog/blog__10.jpg";
import blogImage14 from "@/assets/img/blog/344.jpg";
const getAllBlogs = () => {
  const blogs = [
    {
      id: 1,
      title:
        "தமிழ்நாடு பாஜக மீது தேசிய தலைமை அதிருப்தி! | Chinnappa Ganesan #bjp",
      img: blogImage1,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Management",
      category: "Supply Chain Optimization",
      day: 21,
      publishDate: "10 Dec, 2024",
      date: "Nov, 2024",
      duration: "1500",
      youtubeLink: "https://www.youtube.com/watch?v=zw2mQxY0tt0&t=1s&ab_channel=Channel5Tamil",
    },
    {
      id: 2,
      title: "திருப்புன்கூர் போகலாம் வாங்க! | Thagadur Tamilan | Channel 5",
      img: blogImage10,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Start-up",
      category: "Supply Chain Optimization",
      day: 15,
      publishDate: "11 Dec, 2024",
      date: "August, 2024",
      duration: "1800",
      youtubeLink: "https://www.youtube.com/watch?v=1uYw2mQjpCg",
    },
    {
      id: 3,
      title: "Shekhar Iyer | ``Varahi Certification'' Now or Never",
      img: blogImage14,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Start-up",
      category: "Supply Chain Optimization",
      day: 16,
      publishDate: "12 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
      youtubeLink: "https://www.youtube.com/watch?v=qaXw7Ku5fLQ&t=11s&ab_channel=Channel5India",
    },
    {
      id: 4,
      title:
        "5 Strategies to Transform Your Business with Effective Consulting",
      img: blogImage4,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Management",
      category: "Strategic Planning",
      day: 19,
      publishDate: "14 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
      youtubeLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    {
      id: 5,
      title: "Why Every Startup Needs a Business Consultant",
      img: blogImage5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Consulting",
      category: "Market Entry Strategy",
      day: 12,
      publishDate: "16 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
      youtubeLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    {
      id: 6,
      title: "How Marketing Consultants Can Double Your Revenue in 6 Months",
      img: blogImage6,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Start-up",
      category: "Supply Chain Optimization",
      day: 21,
      publishDate: "16 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
      youtubeLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    {
      id: 7,
      title:
        "The Ultimate Guide to Choosing the Right Marketing Consultant for Your Brand",
      img: blogImage7,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Management",
      category: "Strategic Planning",
      day: 19,
      publishDate: "17 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
      youtubeLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    {
      id: 8,
      title:
        "Corporate Strategy: How to Align Business Goals with Organizational Success",
      img: blogImage8,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Start-up",
      category: "Supply Chain Optimization",
      day: 12,
      publishDate: "18 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
      youtubeLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    {
      id: 9,
      title:
        "The Role of Corporate Culture in Business Growth: A Consultant's Perspective",
      img: blogImage9,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Consulting",
      category: "Market Entry Strategy",
      day: 21,
      publishDate: "27 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
      youtubeLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    {
      id: 10,
      title: "Why Digital Agencies Are the Backbone of Modern Business Growth",
      img: blogImage5,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Management",
      category: "Strategic Planning",
      day: 19,
      publishDate: "14 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
      youtubeLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    {
      id: 11,
      title: "Top 5 Digital Marketing Trends for Agencies in 2024",
      img: blogImage6,
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
      tag: "Consulting",
      category: "Market Entry Strategy",
      day: 12,
      publishDate: "16 Dec, 2024",
      date: "Sep, 2024",
      duration: "2100",
      youtubeLink: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    },
    // {
    //   id: 12,
    //   title:
    //     "How Finance Consulting Can Help Your Business Survive Economic Downturns",
    //   img: blogImage7,
    //   desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
    //   tag: "Marketing",
    //   category: "Financial Restructuring",
    //   day: 21,
    //   publishDate: "16 Dec, 2024",
    //   date: "Sep, 2024",
    //   duration: "2100",
    // },
    // {
    //   id: 13,
    //   title: "The Importance of Financial Planning in Scaling Your Business",
    //   img: blogImage9,
    //   desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
    //   tag: "Consulting",
    //   category: "Market Entry Strategy",
    //   day: 19,
    //   publishDate: "17 Dec, 2024",
    //   date: "Sep, 2024",
    //   duration: "2100",
    // },
    // {
    //   id: 14,
    //   title: "Human Resource Consulting: How to Build a High-Performing Team",
    //   img: blogImage8,
    //   desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
    //   tag: "Management",
    //   category: "Strategic Planning",
    //   day: 12,
    //   publishDate: "18 Dec, 2024",
    //   date: "Sep, 2024",
    //   duration: "2100",
    // },
    // {
    //   id: 15,
    //   title: "The Future of HR: Trends Every Business Needs to Know in 2024",
    //   img: blogImage4,
    //   desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
    //   tag: "Operation",
    //   category: "Business Process",
    //   day: 21,
    //   publishDate: "27 Dec, 2024",
    //   date: "Sep, 2024",
    //   duration: "2100",
    // },
    // {
    //   id: 16,
    //   title: "How Creative Agencies Are Revolutionizing Brand Identity",
    //   img: blogImage6,
    //   desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
    //   tag: "Consulting",
    //   category: "Market Entry Strategy",
    //   day: 19,
    //   publishDate: "14 Dec, 2024",
    //   date: "Sep, 2024",
    //   duration: "2100",
    // },
    // {
    //   id: 17,
    //   title: "The Power of Storytelling in Creative Agency Campaigns",
    //   img: blogImage8,
    //   desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
    //   tag: "HR Management",
    //   category: "Cost Reduction Analysis",
    //   day: 12,
    //   publishDate: "16 Dec, 2024",
    //   date: "Sep, 2024",
    //   duration: "2100",
    // },
    // {
    //   id: 18,
    //   title: "eCommerce Growth Hacks: Insights from Industry Experts",
    //   img: blogImage5,
    //   desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
    //   tag: "Operation",
    //   category: "Business Process",
    //   day: 21,
    //   publishDate: "16 Dec, 2024",
    //   date: "Sep, 2024",
    //   duration: "2100",
    // },
    // {
    //   id: 19,
    //   title: "How to Boost Your eCommerce Sales with Strategic Consulting",
    //   img: blogImage7,
    //   desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
    //   tag: "Marketing",
    //   category: "Financial Restructuring",
    //   day: 19,
    //   publishDate: "17 Dec, 2024",
    //   date: "Sep, 2024",
    //   duration: "2100",
    // },
    // {
    //   id: 20,
    //   title: "Building a Personal Brand: Tips for an Impressive Portfolio",
    //   img: blogImage9,
    //   desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
    //   tag: "Marketing",
    //   category: "Financial Restructuring",
    //   day: 12,
    //   publishDate: "18 Dec, 2024",
    //   date: "Sep, 2024",
    //   duration: "2100",
    // },
    // {
    //   id: 21,
    //   title: "Why a Strong Personal Portfolio is Crucial for Business Success",
    //   img: blogImage4,
    //   desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt.",
    //   tag: "Start-up",
    //   category: "Supply Chain Optimization",
    //   day: 21,
    //   publishDate: "27 Dec, 2024",
    //   date: "Sep, 2024",
    //   duration: "2100",
    // },
  ];
  return blogs;
};

export default getAllBlogs;
